/* beep.c — PWM-based passive piezo buzzer driver
 *
 * Uses the Simple PWM component (sl_pwm) generated by Simplicity Studio.
 * Instance name assumed: "buzzer" -> sl_pwm_buzzer, sl_pwm_buzzer_config.
 *
 * Frequency is changed by reconfiguring the PWM instance's frequency field
 * and re-initializing, since sl_pwm only exposes duty-cycle control on a
 * fixed frequency once initialized. For most beep use-cases a single fixed
 * frequency (BEEP_DEFAULT_FREQ_HZ) configured at Pin Tool / component level
 * is sufficient; Beep_Tone() additionally supports re-init at a custom
 * frequency for melody-style use.
 */

#include "beep.h"
#include "sl_pwm.h"
#include "sl_pwm_instances.h"
#include "cmsis_os2.h"
#include "app_log.h"

static uint32_t s_current_freq_hz = 0;

/* ------------------------------------------------------------------ */
/*  Init                                                                */
/* ------------------------------------------------------------------ */
void Beep_Init(void)
{
    /* sl_pwm_init_instances() (autogen) already called sl_pwm_init() with
     * the Pin Tool / component-configured default frequency and started
     * the timer's compare channel — but it does NOT call sl_pwm_start().
     * Explicitly start it here, silent (0% duty). */
    sl_pwm_start(&sl_pwm_buzzer);
    sl_pwm_set_duty_cycle(&sl_pwm_buzzer, 0);
    s_current_freq_hz = BEEP_DEFAULT_FREQ_HZ;  /* matches component config */
    app_log_info("[beep] PWM started, silent\r\n");
}

/* ------------------------------------------------------------------ */
/*  Blocking beep at default frequency                                 */
/* ------------------------------------------------------------------ */
void Beep(uint32_t duration_ms)
{
    Beep_Tone(BEEP_DEFAULT_FREQ_HZ, duration_ms);
}

/* ------------------------------------------------------------------ */
/*  Blocking beep at a custom frequency                                */
/* ------------------------------------------------------------------ */
void Beep_Tone(uint32_t freq_hz, uint32_t duration_ms)
{
    Beep_Start(freq_hz);
    osDelay(duration_ms);  /* yields to FreeRTOS scheduler, unlike a busy-wait */
    Beep_Stop();
}

/* ------------------------------------------------------------------ */
/*  Start continuous tone (non-blocking)                               */
/* ------------------------------------------------------------------ */
void Beep_Start(uint32_t freq_hz)
{
    /* sl_pwm has no runtime "set frequency" API — frequency is fixed at
     * sl_pwm_init() time. Only re-init if the requested frequency differs
     * from the one currently configured, to avoid unnecessarily tearing
     * down/rebuilding the timer (which can glitch the GPIO briefly). */
    if (freq_hz != s_current_freq_hz) {
        sl_pwm_config_t config = {
            .frequency = freq_hz,
            .polarity  = PWM_ACTIVE_HIGH,
        };

        sl_pwm_deinit(&sl_pwm_buzzer);
        sl_pwm_init(&sl_pwm_buzzer, &config);
        sl_pwm_start(&sl_pwm_buzzer);
        s_current_freq_hz = freq_hz;
    }

    sl_pwm_set_duty_cycle(&sl_pwm_buzzer, BEEP_DEFAULT_DUTY_PCT);
}

/* ------------------------------------------------------------------ */
/*  Stop tone                                                          */
/* ------------------------------------------------------------------ */
void Beep_Stop(void)
{
    sl_pwm_set_duty_cycle(&sl_pwm_buzzer, 0);
}
