/* mpu9265.c — MPU-9265 9-axis IMU driver (I2C) for EFR32xG28
 *
 * Uses the I2CSPM (I2C Simple Poll Mode) component generated by
 * Simplicity Studio. Instance name: "mpu9265" → sl_i2cspm_mpu9265
 */

#include "mpu9265.h"
#include "sl_i2cspm.h"
#include "sl_i2cspm_instances.h"
#include "app_log.h"

/* ------------------------------------------------------------------ */
/*  Low-level I2C helpers                                              */
/* ------------------------------------------------------------------ */

/* Write a single byte to a register */
static bool write_reg(uint8_t reg, uint8_t value)
{
    I2C_TransferSeq_TypeDef seq;
    uint8_t buf[2] = { reg, value };

    seq.addr  = MPU9265_I2C_ADDR << 1;
    seq.flags = I2C_FLAG_WRITE;
    seq.buf[0].data = buf;
    seq.buf[0].len  = 2;

    I2C_TransferReturn_TypeDef ret = I2CSPM_Transfer(sl_i2cspm_mpu9265, &seq);
    return (ret == i2cTransferDone);
}

/* Read 'len' bytes starting at register 'reg' */
static bool read_regs(uint8_t reg, uint8_t *data, uint8_t len)
{
    I2C_TransferSeq_TypeDef seq;

    seq.addr  = MPU9265_I2C_ADDR << 1;
    seq.flags = I2C_FLAG_WRITE_READ;
    seq.buf[0].data = &reg;
    seq.buf[0].len  = 1;
    seq.buf[1].data = data;
    seq.buf[1].len  = len;

    I2C_TransferReturn_TypeDef ret = I2CSPM_Transfer(sl_i2cspm_mpu9265, &seq);
    return (ret == i2cTransferDone);
}

/* Read 'len' bytes from a different I2C address (used for AK8963 magnetometer) */
static bool read_regs_addr(uint8_t i2c_addr, uint8_t reg, uint8_t *data, uint8_t len)
{
    I2C_TransferSeq_TypeDef seq;

    seq.addr  = i2c_addr << 1;
    seq.flags = I2C_FLAG_WRITE_READ;
    seq.buf[0].data = &reg;
    seq.buf[0].len  = 1;
    seq.buf[1].data = data;
    seq.buf[1].len  = len;

    I2C_TransferReturn_TypeDef ret = I2CSPM_Transfer(sl_i2cspm_mpu9265, &seq);
    return (ret == i2cTransferDone);
}

bool MPU9265_TestMagnetometer(void)
{
    /* Enable I2C bypass mode: connects AUX_DA/AUX_CL directly to the
     * primary SDA/SCL bus, so we can talk to AK8963 at address 0x0C
     * as if it were a separate device on the same bus. */

    /* Step 1: disable I2C master mode (USER_CTRL bit 5 = 0) */
    if (!write_reg(MPU9265_REG_USER_CTRL, 0x00u)) {
        app_log_warning("MPU9265: failed to clear USER_CTRL\r\n");
        return false;
    }

    /* Step 2: enable bypass mode (INT_PIN_CFG bit 1 = 1) */
    if (!write_reg(MPU9265_REG_INT_PIN_CFG, 0x02u)) {
        app_log_warning("MPU9265: failed to set bypass mode\r\n");
        return false;
    }

    /* Step 3: try to read AK8963 WHO_AM_I at address 0x0C */
    uint8_t ak_who_am_i = 0;
    if (!read_regs_addr(AK8963_I2C_ADDR, AK8963_REG_WHO_AM_I, &ak_who_am_i, 1)) {
        app_log_info("MPU9265: AK8963 did not respond — no magnetometer present\r\n");
        return false;
    }

    app_log_info("MPU9265: AK8963 WHO_AM_I = 0x%02X (expected 0x%02X)\r\n",
                 ak_who_am_i, AK8963_WHO_AM_I_VALUE);

    if (ak_who_am_i == AK8963_WHO_AM_I_VALUE) {
        app_log_info("MPU9265: magnetometer CONFIRMED — this is a real MPU-9250/9255\r\n");
        return true;
    } else {
        app_log_warning("MPU9265: unexpected AK8963 response\r\n");
        return false;
    }
}

bool MPU9265_ReadWhoAmI(uint8_t *who_am_i)
{
    return read_regs(MPU9265_REG_WHO_AM_I, who_am_i, 1);
}

bool MPU9265_Init(void)
{
    uint8_t who_am_i = 0;

    if (!MPU9265_ReadWhoAmI(&who_am_i)) {
        app_log_warning("MPU9265: I2C read failed\r\n");
        return false;
    }

    app_log_info("MPU9265: WHO_AM_I = 0x%02X\r\n", who_am_i);

    if (who_am_i == MPU9265_WHO_AM_I_MPU6500) {
        app_log_info("MPU9265: detected MPU-6500 (no magnetometer)\r\n");
    } else if (who_am_i == MPU9265_WHO_AM_I_MPU9250) {
        app_log_info("MPU9265: detected MPU-9250\r\n");
    } else if (who_am_i == MPU9265_WHO_AM_I_MPU9255) {
        app_log_info("MPU9265: detected MPU-9255\r\n");
    } else {
        app_log_warning("MPU9265: unrecognized chip ID\r\n");
    }

    /* Wake up sensor: clear sleep bit in PWR_MGMT_1 (0x6B) */
    if (!write_reg(MPU9265_REG_PWR_MGMT_1, 0x00u)) {
        app_log_warning("MPU9265: failed to wake sensor\r\n");
        return false;
    }

    return true;
}

bool MPU9265_ReadData(MPU9265_Data *data)
{
    uint8_t buf[14];

    /* Accel (6 bytes) + temp (2 bytes, skipped) + gyro (6 bytes) */
    if (!read_regs(MPU9265_REG_ACCEL_XOUT_H, buf, 14)) {
        return false;
    }

    data->accel_x = (int16_t)((buf[0] << 8) | buf[1]);
    data->accel_y = (int16_t)((buf[2] << 8) | buf[3]);
    data->accel_z = (int16_t)((buf[4] << 8) | buf[5]);
    /* buf[6],buf[7] = temperature, skipped */
    data->gyro_x  = (int16_t)((buf[8]  << 8) | buf[9]);
    data->gyro_y  = (int16_t)((buf[10] << 8) | buf[11]);
    data->gyro_z  = (int16_t)((buf[12] << 8) | buf[13]);

    return true;
}
